podAnnotations: {}

metrics:
  enabled: false
  podAnnotations: {}

image:
  repository: albe83/llm-gw
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP
  port: 80

podSecurityContext:
  enabled: false
  fsGroup: 1001

containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true


podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []


resourcesPreset: "none"

# Environment variables to be injected via ConfigMap
env:
  PORT: 4000
