name: Build
on:
  workflow_call:
    secrets:
      DH_TOKEN:
        required: true
    outputs:
      registry:
        description: Docker registry
        value: ${{ jobs.build.outputs.registry }}
      namespace:
        description: Docker namespace
        value: ${{ jobs.build.outputs.namespace }}
      image:
        description: Docker image name
        value: ${{ jobs.build.outputs.image }}
      digest:
        description: Image digest
        value: ${{ jobs.build.outputs.digest }}
      tags:
        description: Image tags
        value: ${{ jobs.build.outputs.tags }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      registry: docker.io
      namespace: albe83
      image: llm-gw
    outputs:
      registry: ${{ env.registry }}
      namespace: ${{ env.namespace }}
      image: ${{ env.image }}
      digest: ${{ steps.docker_builder.outputs.digest }}
      tags: ${{ steps.docker_metadata.outputs.tags }}
    steps:
      - name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.namespace }}/${{ env.image }},enable=true
          tags: |
            type=ref,event=tag

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Docker Build and Push
        id: docker_builder
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.docker_metadata.outputs.tags }}
