name: Release Workflow
on:
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets:
      DH_TOKEN: ${{ secrets.DH_TOKEN }}

  provenance:
    needs:
      - build
    uses: ./.github/workflows/provenance.yaml
    with:
      registry: ${{ needs.build.outputs.registry }}
      namespace: ${{ needs.build.outputs.namespace }}
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
    secrets:
      DH_TOKEN: ${{ secrets.DH_TOKEN }}

  sbom:
    needs:
      - build
    uses: ./.github/workflows/sbom.yaml
    with:
      namespace: ${{ needs.build.outputs.namespace }}
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      tag: ${{ github.event.release.tag_name }}
    secrets:
      DH_TOKEN: ${{ secrets.DH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sign:
    needs:
      - build
      - provenance
      - sbom
    uses: ./.github/workflows/sign.yaml
    with:
      namespace: ${{ needs.build.outputs.namespace }}
      digest: ${{ needs.build.outputs.digest }}
      tags: ${{ needs.build.outputs.tags }}
    secrets:
      DH_TOKEN: ${{ secrets.DH_TOKEN }}
