name: Release Workflow
on:
  release:
    types:
      - published
jobs:
  containerization:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC keyless signing
      contents: read    # required to fetch code
    env:
      IMAGE_NAME: llm-gw
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DH_USERNAME }}/${{ env.IMAGE_NAME }},enable=true

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
