name: Sign
on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      digest:
        required: true
        type: string
      tags:
        required: true
        type: string
    secrets:
      DH_TOKEN:
        required: true

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      cosign-release: 'v2.5.3'
      namespace: ${{ inputs.namespace }}
      digest: ${{ inputs.digest }}
      tags: ${{ inputs.tags }}
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.namespace }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: ${{ env.cosign-release }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ env.digest }}
          TAGS: ${{ env.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
